"""
cron_manager.py  v2.0
---------------------
Manages the biweekly cron job that auto-runs the scanner.
Writes to /etc/cron.d/arrstack-scanner (preferred) or user crontab.
"""
from __future__ import annotations

import os, shutil, subprocess
from pathlib import Path

CRON_D_FILE = Path('/etc/cron.d/arrstack-scanner')
CRON_MARKER = '# arrstack-media-scanner'
SCANNER     = Path('/app/media_scan.py')
LOG_FILE    = Path('/mnt/reports/cron.log')

CAT_ENV_MAP = {
    'shows':      'MEDIA_SHOWS',
    'movies':     'MEDIA_MOVIES',
    'anime':      'MEDIA_ANIME',
    'books':      'MEDIA_BOOKS',
    'audiobooks': 'MEDIA_AUDIOBOOKS',
    'music':      'MEDIA_MUSIC',
}


def _build_env_str(folder_paths: dict, report_dir: Path) -> str:
    parts = [f'REPORT_DIR={report_dir}']
    for cat, env_key in CAT_ENV_MAP.items():
        if cat in folder_paths:
            parts.append(f'{env_key}={folder_paths[cat]}')
    return ' '.join(parts)


def set_cron(expression: str, folder_paths: dict, report_dir: Path) -> None:
    env_str = _build_env_str(folder_paths, report_dir)
    python  = shutil.which('python3') or '/usr/bin/python3'
    cmd     = f'{env_str} {python} {SCANNER} >> {LOG_FILE} 2>&1'
    line    = f'{expression} root {cmd} {CRON_MARKER}'

    if os.access('/etc/cron.d', os.W_OK):
        CRON_D_FILE.write_text(
            f'{CRON_MARKER}\n# Auto-generated by arrstack-media-scanner GUI\n{line}\n'
        )
        os.chmod(CRON_D_FILE, 0o644)
    else:
        _set_user_crontab(expression, cmd)


def remove_cron() -> None:
    if CRON_D_FILE.exists():
        try: CRON_D_FILE.unlink()
        except PermissionError: pass
    _remove_user_crontab()


def _set_user_crontab(expression: str, cmd: str) -> None:
    result = subprocess.run(['crontab', '-l'], capture_output=True, text=True)
    lines  = [l for l in result.stdout.splitlines() if CRON_MARKER not in l]
    lines.append(f'{expression} {cmd} {CRON_MARKER}')
    new_crontab = '\n'.join(lines) + '\n'
    subprocess.run(['crontab', '-'], input=new_crontab, text=True, check=True)


def _remove_user_crontab() -> None:
    result = subprocess.run(['crontab', '-l'], capture_output=True, text=True)
    if result.returncode != 0: return
    lines = [l for l in result.stdout.splitlines() if CRON_MARKER not in l]
    new_crontab = '\n'.join(lines) + '\n'
    subprocess.run(['crontab', '-'], input=new_crontab, text=True)
